spring.application.name=backend
# H2 Console enable kar rahe hain taaki browser mein DB dikhe
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:financedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# SQL queries terminal mein dikhayega
spring.jpa.show-sql=true